### ISSUE TITLE
Sample issue for testing miscellaneous comment filter

### ISSUE THREAD

**Issue by PTLux1517** [PTLux1517/CS471_Team5_Probot_Testing#2]
Posting comments below that are
* one word
* only symbols
* predetermined spam

should trigger a response from Do-It-All-Bot.

**Comment by PTLux1517** [comment]
One-word

**Comment by PTLux1517** [comment]
One-word

**Comment by PTLux1517** [comment]
An acceptable comment

**Comment by PTLux1517** [comment]
#$%&*^!

**Comment by ChaseStauts** [comment]
%%#!!!

**Comment by ChaseStauts** [comment]
#$%&*^!

**Comment by ChaseStauts** [comment]
#$%&*^!

**Comment by ChaseStauts** [comment]
#$%&*^!

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
#$%&*^!

**Comment by PTLux1517** [comment]
yeah

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
💯

**Comment by PTLux1517** [comment]
🧇 🥛

**Comment by PTLux1517** [comment]
yeah

**Comment by PTLux1517** [comment]
#$%&*^!

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/

**Comment by PTLux1517** [comment]
#$%&*^!

**Comment by PTLux1517** [comment]
yeah

**Comment by PTLux1517** [comment]
hey check out my website: https://bouncingdvdlogo.com/
