### ISSUE TITLE
Sample issue for testing emoticon filter

### ISSUE THREAD

**Issue by PTLux1517** [PTLux1517/CS471_Team5_Probot_Testing#3]
Posting comments below that correspond to
* traditional symbolic emoticons (e.g. :) )
* word-based emoticons (e.g., cloud)

should trigger a response from Do-It-All-Bot.

**Comment by PTLux1517** [comment]
Okay, you've got a point. Using a bit mask and running on bare metal uses less ram.

**Comment by PTLux1517** [comment]
Okay, you've got a point. Using a bit mask and running on bare metal uses less ram.

**Comment by PTLux1517** [comment]
Why run python in the cloud, when you can write a Docker file factory in Java and ship your code for Windows, Apple, and Linux?

**Comment by PTLux1517** [comment]
...says the guy from "Sun Microsystems"

**Comment by quinnshultz** [comment]
:)

**Comment by quinnshultz** [comment]
:(

**Comment by PTLux1517** [comment]
:)
